[package]
name = "dellingr"
version = "0.1.0"
edition = "2024"
description = "An embeddable, pure-Rust Lua VM with precise instruction-cost accounting"
license = "MIT"
repository = "https://github.com/folknor/dellingr"

[features]
debug_parser = []
debug_vm = []
debug_gc = []

[dependencies]
rand = "0.8"
lua-patterns = "0.4"
indexmap = "2.0"
slotmap = "1.1"
